FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

ARG FRONTEND_PORT
ARG BACKEND_PORT
ENV NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
ENV NEXT_PUBLIC_BACKEND_PORT=${BACKEND_PORT}

# Print port values
RUN echo "FRONTEND_PORT: ${FRONTEND_PORT}"
RUN echo "BACKEND_PORT: ${BACKEND_PORT}"

EXPOSE ${FRONTEND_PORT}

# Use shell form to ensure environment variable expansion
CMD sh -c "npm run dev -- -p ${FRONTEND_PORT}"
