name: code checks

on:
  push:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - '**.py'
      - '**.tsx'
      - poetry.lock
      - pyproject.toml
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/code_checks.yml
      - '**.py'
      - '**.tsx'
      - poetry.lock
      - pyproject.toml

jobs:
  run-code-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.0
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.10'
          cache: 'poetry'
      - uses: actions/setup-node@v4.0.4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      - name: Install dependencies and check code
        run: |
          cd backend
          poetry env use '3.10'
          source .venv/bin/activate
          poetry install --with test --all-extras
          pre-commit run --all-files
      - name: pip-audit (gh-action-pip-audit)
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          virtual-environment: .venv/
